### ISSUE TITLE
glow/esp

### ISSUE THREAD

**Issue by SoTMaulder** [IntelSDM/HuntDMA#1]
neither are working for me, using a  https://shop.lambdaconcept.com/home/50-screamer-pcie-squirrel.html

**Comment by IntelSDM** [comment]
Sounds like entities aren't being added to the playerlist. Add some debug prints to check if any are added.  If no ESP is working then something is very wrong and it is likely that there is a failure to read something.  Just spam out debug prints and try and see whats going on with it.

**Comment by SoTMaulder** [comment]
> Sounds like entities aren't being added to the playerlist. Add some debug prints to check if any are added. If no ESP is working then something is very wrong and it is likely that there is a failure to read something. Just spam out debug prints and try and see whats going on with it.

aight i gotchu, busy atm, but ill get to it in a little bit

**Comment by Sevenn83** [comment]
I've put some debug and log to see, I can confirm, sometime the playerlist is empty, and the zombielist is imcomplete. Forcing a restart end on the same result, it's really weird.
