### ISSUE TITLE
Hunt Showdown——Hunt: Showdown 1896

### ISSUE THREAD

**Issue by NianGaoZai** [IntelSDM/HuntDMA#22]
Engine change. Can you update it.

**Comment by RyanAMTB** [comment]
You are on your own my friend, have you tried updating the offset yet?

**Comment by NianGaoZai** [comment]
I updated the offset,I game into the black screen.cry

**Comment by NianGaoZai** [comment]
A problem with my game, I don't know if my updated offset will work,I can't log in to the game

**Comment by NianGaoZai** [comment]
uint64_t SystemGlobalEnvironment = 0x26782F8; 
uint64_t EntitySystem = 0xC0;
uint64_t pSystem = 0x90;
uint16_t ObjectCount = 0x0;
uint64_t EntityList = 0xC0;
uint16_t ObjectCountOffset = 0x40092;
uint64_t EntityListOffset = 0x40098;

uint64_t CameraBase = 0x928;
uint64_t ViewMatrixOffset = 0x230;
uint64_t CameraPosOffset = 0x2F0;
uint64_t ProjectionMatrixOffset = 0x270;

Where else do I need to update the offset？？？？？？？？？？？？？？
