### ISSUE TITLE
Where else do I need to update the offset?

### ISSUE THREAD

**Issue by NianGaoZai** [IntelSDM/HuntDMA#23]
uint64_t SystemGlobalEnvironment = 0x26782F8;
uint64_t EntitySystem = 0xC0;
uint64_t pSystem = 0x90;
uint16_t ObjectCount = 0x0;
uint64_t EntityList = 0xC0;
uint16_t ObjectCountOffset = 0x40092;
uint64_t EntityListOffset = 0x40098;

uint64_t CameraBase = 0x928;
uint64_t ViewMatrixOffset = 0x230;
uint64_t CameraPosOffset = 0x2F0;
uint64_t ProjectionMatrixOffset = 0x270;

**Comment by zekrui** [comment]
Have you found any more updated offsets? also working on it

**Comment by asdat3** [comment]
anyone found anything? environment.h and camera.h I should have completed but it still doesnt show anything :(

**Comment by NianGaoZai** [comment]
Debugging Window:
inizializing...
dumping memory map to file...
Dumped memory map!
DEVICE: FPGA: Enigma X1 PCIe gen1 x1 [250,10,500] [v4.13,0400] [ASYNC,NORM,FWCUST]
[SYMBOL]   Functionality may be limited. Extended debug information disabled.
[SYMBOL]   Offline symbols unavailable - file 'info.db' not found.
[SYMBOL]   Reason: Could not load PDB required file - symsrv.dll/dbghelp.dll.
[SYMBOL]   Reason: Could not load PDB required file - libpdbcrust.dll/so.

Initialized 64-bit Windows 10.0.19041
FPGA ID: 9
DEVICE ID: 1024
success!
[CORE]     VmmProc: Start periodic cache flushing
[+] VMMDLL_ConfigGet ID = 9 VERSION = 0.0
[VMM]      VirtualStorePageFileNumber: WARN! did not find virtual store number - fallback to default
CR3 fixed
[+] Found Base Address for HuntGame.exe at 0x00007FF63BA10000
[+] Found Base Size for HuntGame.exe at 0x00000000031AC000
Process information of HuntGame.exe
PID: 5812
Base Address: 0x00007FF63BA10000
Base Size: 0x00000000031AC000
HuntGame: 0x3BA10000
[+] Found Base Address for GameHunt.dll at 0x00007FFAFA570000
GameHunt: 0xFA570000
win10
eat_map->cMap: 2460
Connecting to KMBOX on port \\.\
Serial handle: -1
Failed to open serial port!
win10
eat_map->cMap: 2460
Connecting to KMBOX on port \\.\
Serial handle: -1
Failed to open serial port!
SystemGlobalEnvironment: 0x3DFEDEB0
EntitySystem: 0x8AC96E0
pSystem: 0x39084FD8
SystemGlobalEnvironment: 0x3DFEDEB0
EntitySystem: 0x8AC96E0
pSystem: 0x39084FD8
ObjectCount: 7910
ObjectCount: 7910

It can be turned on, but it's still not in the game

**Comment by asdat3** [comment]
yep same here, it even changes the object count depending on if you are in a lobby or main menu

**Comment by NianGaoZai** [comment]
That means there's something wrong with the offset

**Comment by NianGaoZai** [comment]
I don't know what went wrong

**Comment by asdat3** [comment]
sadly havent found any other projects, just wanted to test it while the free weekend

**Comment by NianGaoZai** [comment]
Have you had any success

**Comment by asdat3** [comment]
nah made my own, this stuff is too big to fix urself

**Comment by NianGaoZai** [comment]
> 没有我自己做的，这东西太大了，自己修不起来

Can you publish it? I really need this cheat

**Comment by NianGaoZai** [comment]
> nah made my own, this stuff is too big to fix urself

Can you publish it? I really need this cheat

**Comment by asdat3** [comment]
https://www.unknowncheats.me/forum/members/3621479.html write me a pm

**Comment by NianGaoZai** [comment]
I left a message.

**Comment by Ben-John933** [comment]
> 我留言了。
我修复了chams,其他的功能我也无能为力,你需要吗

**Comment by asdat3** [comment]
didnt get either of your messages, are you sure the message went out? else contact me on discord: kyudev (penguin profile picture)

**Comment by Ben-John933** [comment]
> I left a message.

https://github.com/Ben-John933/DMAByDaylight
我已经上传了

**Comment by NianGaoZai** [comment]
> > 我留言了。
> 
> https://github.com/Ben-John933/DMAByDaylight 我已经上传了
You posted ByDaylight

**Comment by NianGaoZai** [comment]
We are talking about Hunt:Showdown

**Comment by Ben-John933** [comment]
> We are talking about Hunt:Showdown

请看看main里新上传的文件

**Comment by NianGaoZai** [comment]
> > 我们正在谈论 Hunt：Showdown
> 
> 请看看main里新上传的文件

我试过了。但没有成功

**Comment by Ben-John933** [comment]
> > > 我们正在谈论 Hunt：Showdown
> > 
> > 
> > 请看看main里新上传的文件
> 
> 我试过了。但没有成功

我检查了文件,没有传错,只有charm功能可以使用,如果进对局没有charm应该是mem out了需要重启,请进入射击场测试,这是绝对可用的,已经测试过很多次

**Comment by NianGaoZai** [comment]
> > > > 我们正在谈论 Hunt：Showdown
> > > 
> > > 
> > > 请看看main里新上传的文件
> > 
> > 
> > 我试过了。但没有成功
> 
> 我检查了文件，没有传错，只有charm功能可以使用，如果进对局没有charm应该是mem out了需要重启，请进入射击场测试，这是绝对可用的，已经测试过很多次

[!] Couldn't find Base Address for GameHunt.dll
SystemGlobalEnvironment: 0x0
EntitySystem: 0x0
pSystem: 0x0
ObjectCount: 0

It's incorrect

**Comment by asdat3** [comment]
tf u guys doin? xD

**Comment by NianGaoZai** [comment]
Yours is fine，I made a mistake，I'd like to study your code.Can you upload your code？

**Comment by Ben-John933** [comment]
> > > > 我们正在谈论 Hunt：Showdown
> > > 
> > > 
> > > 请看看main里新上传的文件
> > 
> > 
> > 我试过了。但没有成功
> 
> 我检查了文件,没有传错,只有charm功能可以使用,如果进对局没有charm应该是mem out了需要重启,请进入射击场测试,这是绝对可用的,已经测试过很多次

我把源码压缩包给你,只做了几行修改,稍等,我在上传

**Comment by NianGaoZai** [comment]
thank you

**Comment by Ben-John933** [comment]
> tf u guys doin? xD



> thank you

https://github.com/Ben-John933/DMAByDaylight
查看main新上传的文件

**Comment by Whitebrim** [comment]
> https://www.unknowncheats.me/forum/members/3621479.html write me a pm

Sorry, you can only send messages to UnKnoWnCheaTs staff until you have 4 posts.
