### ISSUE TITLE
Hunt: Showdown Esp Features

### ISSUE THREAD

**Issue by spookykokojunge** [IntelSDM/HuntDMA#3]
Hello IntelSDM, finally, there is a DMA cheat available for Hunt Showdown. 
I wanted to inform you that instead of a supply ESP, you actually need a cash register ESP and boss ESP as you find the supply boxes everywhere. Additionally, I noticed that other DMA cheats display player silhouettes over zombies and bosses.

And could you please tell me how you obtain the offsets of objects like the supply box? I'm unsure how to search for them.

**Comment by IntelSDM** [comment]
We use the names to find the objects within the environment CacheEntities function. 
If you want to add something new to the ESP then you need to add it to the cache by getting the entity or class name.
You print entity name with: printf(LIT("Entity Name: %s\n"), ent->GetEntityName().name);
Your print entity class name with: printf(LIT("Entity ClassName: %s\n"), ent->GetEntityClassName().name);
Once you find the name of what you want you then add it to a list from the CacheEntities function.

To add silhouettes to zombies then you call: 
ent->WriteNode(writehandle, Configs.Player.ChamMode);

In the UpdateZombieList function before you call the updatenode function. 
So its done the exact same way as it is done for players.

**Comment by spookykokojunge** [comment]
Thanks for the fast answer. So, I added 'ent->WriteNode(writehandle, Configs.Player.ChamMode);' before the 'UpdateNode' in the 'UpdateZombieList'. However, it doesn't seem to work. I added it in the 'Environment.cpp'.

And one question: Do you think I can also write the player chams over objects like the supply box, for example?

**Comment by IntelSDM** [comment]
If you are using an older version then there was a check on the rendernode, remove that and it will work(In the WriteNode function).
You can put chams on any object.

**Comment by IntelSDM** [comment]
It uses the strings for names, the classes are all in the object list. We just read the class name to find the pointer to the entity.

**Comment by spookykokojunge** [comment]
Ah, I see. So if I were to add 'cash_register' or 'cashregister' to the list, along with adding an if statement for the cash register, it would probably find the actual cash registers in the game, am I right?

And how did you find those? Did you use dnSpy to look in the object list?

**Comment by muhan121** [comment]
能否制作一个无dma 的 猎杀 对决
