### ISSUE TITLE
[!] Failed to open a VMM Handle dumping memory map to file... [!] ERROR: Could not dump memory map!

### ISSUE THREAD

**Issue by FanXingyyds** [IntelSDM/HuntDMA#5]
[!] Failed to open a VMM Handle
dumping memory map to file...
[!] ERROR: Could not dump memory map!

**Comment by IntelSDM** [comment]
You are probably on an AMD CPU or don't have a DMA card. If you don't have a DMA card then you need to buy one to use the cheat. If you have one but are on a certain AMD CPU, you might need to manually generate your own mmap.txt.
