### ISSUE TITLE
Can you please add a function?

### ISSUE THREAD

**Issue by dongerlel** [IntelSDM/HuntDMA#8]
Hello.
Can you add a visibility check for chams? this game is way too easy if you always have 100% information. Just a visual indicator when you actually see the enemy on the scree would be enough.

**Comment by IntelSDM** [comment]
I am currently HWID banned so I don't really have an interest in persisting with the cheat. That being said in nearly all games visibility is extremely difficult to measure externally. Rather you can implement a FOV circle for ESP so it will only render people within that circle or add binds or a minimum distance check.
