### ISSUE TITLE
environment code not working :(

### ISSUE THREAD

**Issue by onyamom** [IntelSDM/HuntDMA#9]
the updated environment code 0x59A96D0 however no good when booting up game getting

SystemGlobalEnvironment: 0x0
EntitySystem: 0x0
pSystem: 0x0
ObjectCount: 0

does huntdma.exe + huntdma.pdb need to be updated?

**Comment by IntelSDM** [comment]
I messed systemglobalenvironment up, I just pushed an update. Try that.

**Comment by onyamom** [comment]
i just tried it and same relooping codes :(

**Comment by onyamom** [comment]
can you confirm its working for you? cause im wondering if its an issue with my firmware..

**Comment by IntelSDM** [comment]
That is unfortunate. You could probably just ask on Unknowncheats. I don't have the game installed and I am HWID banned so I can't even get into the main menu unless i buy a new account.

**Comment by onyamom** [comment]
:( damn i'm probably the worst example to be testing this...I got hwid banned as well but i ended up running a permanent hardware id changer so i can get back in the game but im wondering if it fkd the DMA card by doing the hardware id change or the dma firmware being flashed caused something as i get the message CORE "initialization failed. unable to to locate valid DTB. #2" plus i also get "[!] Initialization failed with memory map? try without MMap" aim stuck not knowing if its the offset, my dma is screwed cause of the hwid change or cause of the firmware id change...

**Comment by onyamom** [comment]
i tried your dead by daylight dma and similar thing nothing on radar except for the interface but chams was the only thing showing on main screen

**Comment by onyamom** [comment]
all good i been active on there waiting on both your post and the main one to look out for
